---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: tituba-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # You can pin to a specific version of Fedora as well

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: common/removing.yml
  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - starship
        - espanso-wayland
        - steam
        - brave-origin
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.dec05eba.gpu_screen_recorder
      - notify: true
        scope: user # Also add Flathub user repo, but no user packages
        install:
          - cc.arduino.IDE2
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          - org.raspberrypi.rpi-imager
          - org.telegram.desktop
          - org.videolan.VLC
          - org.openscad.OpenSCAD
          - org.kde.okular
          - org.kde.kcalc
          - org.kde.gwenview
          - org.kde.filelight
          - io.github.wdaniau.fstl
          - io.github.tobagin.keysmith
          - com.orcaslicer.OrcaSlicer
          - io.github.pwr_solaar.solaar
          - dev.lizardbyte.app.Sunshine
          - com.transmissionbt.Transmission
          - io.m51.Gelly
          - com.github.xournalpp.xournalpp
          - com.vysp3r.ProtonPlus
          - io.ente.auth
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - io.github.giantpinkrobots.flatsweep
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - org.freecad.FreeCAD
          - com.github.tchx84.Flatseal
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
