# yaml-language-server: $schema=https://schema.blue-build.org/module-list-v1.json
modules:
  - type: dnf
    repos:
      copr:
        - fovty/hushmic
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      packages:
        - espanso-wayland
        - steam
        - brave-origin
        - syncthing
        - tailscale
        - hushmic
        - okular
        - kcalc
        - gwenview
        - filelight
        - solaar
        - transmission-qt
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.dec05eba.gpu_screen_recorder
      - notify: true
        scope: user # Also add Flathub user repo, but no user packages
        install:
          - cc.arduino.IDE2
          - com.discordapp.Discord
          - com.github.tchx84.Flatseal
          - org.raspberrypi.rpi-imager
          - org.telegram.desktop
          - org.videolan.VLC
          - org.openscad.OpenSCAD
          - io.github.wdaniau.fstl
          - io.github.tobagin.keysmith
          - com.orcaslicer.OrcaSlicer
          - dev.lizardbyte.app.Sunshine
          - io.m51.Gelly
          - com.github.xournalpp.xournalpp
          - com.vysp3r.ProtonPlus
          - io.ente.auth
          - io.github.DenysMb.Kontainer
          - io.github.flattool.Warehouse
          - io.github.giantpinkrobots.flatsweep
          - it.mijorus.gearlever
          - md.obsidian.Obsidian
          - org.freecad.FreeCAD
